# -*- coding: utf-8 -*-
"""HayamAlrashed_437201723_Assignment #3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ub3f1DQ5VAF1QJt9WVL37SzaW3nfv_MO
"""

# -*- coding: utf-8 -*-
"""4_Students preprocessing(IT469)FINAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12MLfmvlY9VHX4JuJowef0xL_6P63qfBv
"""

!pip install pyarabic #A specific Arabic language library for Python, provides basic functions to manipulate Arabic letters and text, like detecting Arabic letters, Arabic letters groups and characteristics, remove diacritics etc.
import pyarabic.araby as araby
import re
import string #for string.punctuation


emoji_pattern = re.compile("["
    "\U0001F1E0-\U0001F1FF"  # flags (iOS)
    "\U0001F300-\U0001F5FF"  # symbols & pictographs
    "\U0001F600-\U0001F64F"  # emoticons
    "\U0001F680-\U0001F6FF"  # transport & map symbols
    "\U0001F700-\U0001F77F"  # alchemical symbols
    "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
    "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
    "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
    "\U0001FA00-\U0001FA6F"  # Chess Symbols
    "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
    "\U00002702-\U000027B0"  # Dingbats
    "\U000024C2-\U0001F251" 
    "]+" , flags=re.UNICODE)

def clean(text): 
    #Remove URLs Q1
    #Remove emails Q2
    #Remove Mentions Q3
    #Remove Emojis


    #Remove URLs Q1
    text = re.sub('https?://(?:[a-zA-Z]|[0-9]|[/_.%])+',"",text)
    #Remove emails Q2
    text = re.sub(r'[\w\.-]+@[\w\.-]+',"",text)
    #Remove Mentions Q3
    text = re.sub(r"@([A-Za-z0-9_-]+)", "", text)
    
    #remove hashtag 
    text = re.sub(r'#\w+ ?', "", text)

    text = re.sub(emoji_pattern, "", text)
    text = re.sub('emoji[0-9][0-9][0-9]', '', text) #remove emoji encodings
    #Remove English letters 
    if re.match("#(\w+)",text) == None: 
      text = re.sub("[A-Za-z]", "", text)
      #translate numbers
      text = re.sub("0", "٠", text)
      text = re.sub("1", "١", text)
      text = re.sub("2", "٢", text)
      text = re.sub("3", "٣", text)
      text = re.sub("4", "٤", text)
      text = re.sub("5", "٥", text)
      text = re.sub("6", "٦", text)
      text = re.sub("7", "٧", text)
      text = re.sub("8", "٨", text)
      text = re.sub("9", "٩", text)
    

    return(text)


def normalizeArabic(text):
    #Normalize
    text = re.sub("[إأٱآا]", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("[يى]", "ي", text)
    text = re.sub("[ئؤ]", "ء", text)
    return(text)

def remove_tatweel(text):
    text = re.sub("[«»،؟,ـ]", "", text)
    #Remove repeated letters Q4
    text = re.sub("ا+","ا",text)
    text = re.sub("ب+","ب",text)
    text = re.sub("ت+","ت",text)
    text = re.sub("ث+","ث",text)
    text = re.sub("ج+","ج",text)
    text = re.sub("ح+","ح",text)
    text = re.sub("خ+","خ",text)
    text = re.sub("د+","د",text)
    text = re.sub("ذ+","ذ",text)
    text = re.sub("ر+","ر",text)
    text = re.sub("ز+","ز",text)
    text = re.sub("س+","س",text)
    text = re.sub("ص+","ص",text)
    text = re.sub("ض+","ض",text)
    text = re.sub("ش+","ش",text)
    text = re.sub("ط+","ط",text)
    text = re.sub("ظ+","ظ",text)
    text = re.sub("ع+","ع",text)
    text = re.sub("غ+","غ",text)
    text = re.sub("ف+","ف",text)
    text = re.sub("ق+","ق",text)
    text = re.sub("ك+","ك",text)
    text = re.sub("ل+","ل",text)
    text = re.sub("م+","م",text)
    text = re.sub("ن+","ن",text)
    text = re.sub("ه+","ه",text)
    text = re.sub("و+","و",text)
    text = re.sub("ي+","ي",text)
    text = re.sub("ء+","ء",text)
    text = re.sub("ئ+","ي",text)
    text = re.sub("ى+","ي",text)
    return(text)

#Remove Punctuation (use 1 first (without removing URLs), and 2 second (with removing URLs), and save them separately as 2 versions)

 
#1#
exclude = set(string.punctuation+'؟،٪؛') 
#2#
#exclude = set(string.punctuation+ '١٢٣٤٥٦٧٨٩٠؟،٪؛') #string.punctuation will give all sets of punctuation.


#Example
text= "@nora12 https://122a.a %$?> شجررررةً أرنب سلمى لؤي أنـــــــــآ #يبــأـلًًسيل ١٢٣ emoji245 gkhfh nora88@gmail.com 0530530177 #afg_adf #kajdg111"
text=text.split()
for txt in text:
  txt= clean(txt)
  txt= normalizeArabic(txt)
  txt= araby.strip_tashkeel(txt)
  if re.match("#(\w+)",txt) == None:
    txt= remove_tatweel(txt)
    txt= ''.join(ch for ch in txt if ch not in exclude) #Join all items in a tuple into a string
  print(txt)

with open("Arabic_Tweets(1).txt", encoding="utf-16") as f:
    data = f.read().splitlines()

data

Arabic = []
for x in data :
  AR_txt = clean(x)
  AR_txt = normalizeArabic(AR_txt)
  AR_txt = remove_tatweel(AR_txt)
  AR_txt=  araby.strip_tashkeel(AR_txt)
  Arabic.append(AR_txt)
  #print (AR_txt)

Arabic

with open("Arabic_Proc.txt", "w") as output:
    output.write(str(Arabic))